---
abstract: 'BeLike other CPAN Authors'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-ToBeLike
requires:
  Acme::CPANAuthors: 0
  perl: 5.006002
resources:
  homepage: http://github.com/bingos/acme-cpanauthors-tobelike
  repository: http://github.com/bingos/acme-cpanauthors-tobelike
version: 0.12
