---
abstract: 'BeLike other CPAN Authors'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-CPANAuthors-ToBeLike
requires:
  Acme::CPANAuthors: '0'
  perl: '5.006002'
resources:
  homepage: https://github.com/bingos/acme-cpanauthors-tobelike
  repository: https://github.com/bingos/acme-cpanauthors-tobelike.git
version: '0.44'
